[package]
name = "ssh-config"
version = "0.1.0"
authors = ["ttymck <tyler@tylerkontra.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
dirs = "2.0.2"
